name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-inventory-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: order-service
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag inventory-service:$(date +%s)

  build-orchestrator-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: order-service
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag orchestrator-service:$(date +%s)

  build-order-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: order-service
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag order-service:$(date +%s)

  build-payment-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: order-service
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag payment-service:$(date +%s)

  build-product-validation-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: order-service
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag product-validation-service:$(date +%s)
