name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-inventory-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: inventory-service
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  build-orchestrator-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: orchestrator-service
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  build-order-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: order-service
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  build-payment-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: payment-service
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  build-product-validation-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: product-validation-service
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
