name: Build Múltiplos Projetos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-inventory-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: inventory-service
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build Inventory Service
        run: ./gradlew build

  build-orchestrator-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: orchestrator-service
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build Orchestrator Service
        run: ./gradlew build

  build-order-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: order-service
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build Order Service
        run: ./gradlew build

  build-payment-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: payment-service
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build Payment Service
        run: ./gradlew build

  build-product-validation-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: product-validation-service
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build Product Validation Service
        run: ./gradlew build
